// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.mobila.im.models;

import be.mobila.im.models.ImRequest;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ImRequestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ImRequestDataOnDemand: @Component;
    
    private Random ImRequestDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ImRequest> ImRequestDataOnDemand.data;
    
    public ImRequest ImRequestDataOnDemand.getNewTransientImRequest(int index) {
        be.mobila.im.models.ImRequest obj = new be.mobila.im.models.ImRequest();
        obj.setImuser(null);
        obj.setInsurance(null);
        obj.setPerson(null);
        obj.setRequestDate(new java.util.Date());
        obj.setRequestFor(null);
        obj.setRequestMode(null);
        obj.setUri("uri_" + index);
        return obj;
    }
    
    public ImRequest ImRequestDataOnDemand.getSpecificImRequest(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ImRequest obj = data.get(index);
        return ImRequest.findImRequest(obj.getId());
    }
    
    public ImRequest ImRequestDataOnDemand.getRandomImRequest() {
        init();
        ImRequest obj = data.get(rnd.nextInt(data.size()));
        return ImRequest.findImRequest(obj.getId());
    }
    
    public boolean ImRequestDataOnDemand.modifyImRequest(ImRequest obj) {
        return false;
    }
    
    public void ImRequestDataOnDemand.init() {
        data = be.mobila.im.models.ImRequest.findImRequestEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ImRequest' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<be.mobila.im.models.ImRequest>();
        for (int i = 0; i < 10; i++) {
            be.mobila.im.models.ImRequest obj = getNewTransientImRequest(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
