// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.mobila.im.models;

import be.mobila.im.models.ImRequestDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImRequestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImRequestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImRequestIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ImRequestIntegrationTest: @Transactional;
    
    @Autowired
    private ImRequestDataOnDemand ImRequestIntegrationTest.dod;
    
    @Test
    public void ImRequestIntegrationTest.testCountImRequests() {
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", dod.getRandomImRequest());
        long count = be.mobila.im.models.ImRequest.countImRequests();
        org.junit.Assert.assertTrue("Counter for 'ImRequest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImRequestIntegrationTest.testFindImRequest() {
        be.mobila.im.models.ImRequest obj = dod.getRandomImRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to provide an identifier", id);
        obj = be.mobila.im.models.ImRequest.findImRequest(id);
        org.junit.Assert.assertNotNull("Find method for 'ImRequest' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ImRequest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImRequestIntegrationTest.testFindAllImRequests() {
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", dod.getRandomImRequest());
        long count = be.mobila.im.models.ImRequest.countImRequests();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ImRequest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<be.mobila.im.models.ImRequest> result = be.mobila.im.models.ImRequest.findAllImRequests();
        org.junit.Assert.assertNotNull("Find all method for 'ImRequest' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ImRequest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImRequestIntegrationTest.testFindImRequestEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", dod.getRandomImRequest());
        long count = be.mobila.im.models.ImRequest.countImRequests();
        if (count > 20) count = 20;
        java.util.List<be.mobila.im.models.ImRequest> result = be.mobila.im.models.ImRequest.findImRequestEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ImRequest' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ImRequest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImRequestIntegrationTest.testFlush() {
        be.mobila.im.models.ImRequest obj = dod.getRandomImRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to provide an identifier", id);
        obj = be.mobila.im.models.ImRequest.findImRequest(id);
        org.junit.Assert.assertNotNull("Find method for 'ImRequest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImRequest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ImRequest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImRequestIntegrationTest.testMerge() {
        be.mobila.im.models.ImRequest obj = dod.getRandomImRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to provide an identifier", id);
        obj = be.mobila.im.models.ImRequest.findImRequest(id);
        boolean modified =  dod.modifyImRequest(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        be.mobila.im.models.ImRequest merged = (be.mobila.im.models.ImRequest) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ImRequest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImRequestIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", dod.getRandomImRequest());
        be.mobila.im.models.ImRequest obj = dod.getNewTransientImRequest(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ImRequest' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ImRequest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImRequestIntegrationTest.testRemove() {
        be.mobila.im.models.ImRequest obj = dod.getRandomImRequest();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ImRequest' failed to provide an identifier", id);
        obj = be.mobila.im.models.ImRequest.findImRequest(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ImRequest' with identifier '" + id + "'", be.mobila.im.models.ImRequest.findImRequest(id));
    }
    
}
