// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.mobila.im.models;

import be.mobila.im.models.Insurance;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect InsuranceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InsuranceDataOnDemand: @Component;
    
    private Random InsuranceDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Insurance> InsuranceDataOnDemand.data;
    
    public Insurance InsuranceDataOnDemand.getNewTransientInsurance(int index) {
        be.mobila.im.models.Insurance obj = new be.mobila.im.models.Insurance();
        obj.setAbstractDataSaver("abstractDataSaver_" + index);
        obj.setConverter("converter_" + index);
        obj.setImportFile("importFile_" + index);
        obj.setInsuranceType(null);
        obj.setPdfTemplate("pdfTemplate_" + index);
        return obj;
    }
    
    public Insurance InsuranceDataOnDemand.getSpecificInsurance(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Insurance obj = data.get(index);
        return Insurance.findInsurance(obj.getId());
    }
    
    public Insurance InsuranceDataOnDemand.getRandomInsurance() {
        init();
        Insurance obj = data.get(rnd.nextInt(data.size()));
        return Insurance.findInsurance(obj.getId());
    }
    
    public boolean InsuranceDataOnDemand.modifyInsurance(Insurance obj) {
        return false;
    }
    
    public void InsuranceDataOnDemand.init() {
        data = be.mobila.im.models.Insurance.findInsuranceEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Insurance' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<be.mobila.im.models.Insurance>();
        for (int i = 0; i < 10; i++) {
            be.mobila.im.models.Insurance obj = getNewTransientInsurance(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
