// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.mobila.im.models;

import be.mobila.im.models.LiaValueDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LiaValueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LiaValueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LiaValueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LiaValueIntegrationTest: @Transactional;
    
    @Autowired
    private LiaValueDataOnDemand LiaValueIntegrationTest.dod;
    
    @Test
    public void LiaValueIntegrationTest.testCountLiaValues() {
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", dod.getRandomLiaValue());
        long count = be.mobila.im.models.LiaValue.countLiaValues();
        org.junit.Assert.assertTrue("Counter for 'LiaValue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LiaValueIntegrationTest.testFindLiaValue() {
        be.mobila.im.models.LiaValue obj = dod.getRandomLiaValue();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to provide an identifier", id);
        obj = be.mobila.im.models.LiaValue.findLiaValue(id);
        org.junit.Assert.assertNotNull("Find method for 'LiaValue' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'LiaValue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LiaValueIntegrationTest.testFindAllLiaValues() {
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", dod.getRandomLiaValue());
        long count = be.mobila.im.models.LiaValue.countLiaValues();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'LiaValue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<be.mobila.im.models.LiaValue> result = be.mobila.im.models.LiaValue.findAllLiaValues();
        org.junit.Assert.assertNotNull("Find all method for 'LiaValue' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'LiaValue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LiaValueIntegrationTest.testFindLiaValueEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", dod.getRandomLiaValue());
        long count = be.mobila.im.models.LiaValue.countLiaValues();
        if (count > 20) count = 20;
        java.util.List<be.mobila.im.models.LiaValue> result = be.mobila.im.models.LiaValue.findLiaValueEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'LiaValue' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'LiaValue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LiaValueIntegrationTest.testFlush() {
        be.mobila.im.models.LiaValue obj = dod.getRandomLiaValue();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to provide an identifier", id);
        obj = be.mobila.im.models.LiaValue.findLiaValue(id);
        org.junit.Assert.assertNotNull("Find method for 'LiaValue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLiaValue(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'LiaValue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LiaValueIntegrationTest.testMerge() {
        be.mobila.im.models.LiaValue obj = dod.getRandomLiaValue();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to provide an identifier", id);
        obj = be.mobila.im.models.LiaValue.findLiaValue(id);
        boolean modified =  dod.modifyLiaValue(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        be.mobila.im.models.LiaValue merged = (be.mobila.im.models.LiaValue) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'LiaValue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LiaValueIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", dod.getRandomLiaValue());
        be.mobila.im.models.LiaValue obj = dod.getNewTransientLiaValue(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'LiaValue' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'LiaValue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LiaValueIntegrationTest.testRemove() {
        be.mobila.im.models.LiaValue obj = dod.getRandomLiaValue();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LiaValue' failed to provide an identifier", id);
        obj = be.mobila.im.models.LiaValue.findLiaValue(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'LiaValue' with identifier '" + id + "'", be.mobila.im.models.LiaValue.findLiaValue(id));
    }
    
}
